name: Test

on:
  push:

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - redmine-repository: 'redmica/redmica'
            redmine-version: 'stable-3.0'
            ruby-version: '3.2'
          - redmine-repository: 'redmica/redmica'
            redmine-version: 'master'
            ruby-version: '3.2'
          - redmine-repository: 'redmine/redmine'
            redmine-version: 'master'
            ruby-version: '3.2'

    steps:
    - uses: hidakatsuya/action-setup-redmine@v1
      with:
        repository: ${{ matrix.redmine-repository }}
        version: ${{ matrix.redmine-version }}
        ruby-version: ${{ matrix.ruby-version }}
        database: 'postgres:14'

    - uses: actions/checkout@v4
      with:
        path: plugins/redmine_playwright_sample

    - name: Set up plugin
      run: |
        bundle install

    - uses: actions/setup-node@v4

    - name: Install playwright browsers
      run: |
        npm install
        npx playwright install chromium
        npx playwright install-deps

    - name: Run tests
      run: RAILS_ENV=test bundle exec rake test TEST=plugins/redmine_playwright_sample

    - name: Store screenshots Artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-failure-screenshots
        path: /home/runner/work/redmine_playwright_sample/redmine_playwright_sample/tmp/screenshots
        retention-days: 1